require('options')
require('keybindings')
require('plugins')
if not vim.g.vscode then
require('blankline-config')
require('lsp')
require('lualine-config')
require('bufferline-config')
require('telescope-config')
require('octo-config')
require('dap-config')
require('live-preview-config')
require('terminal-config')
require('vscode-theme')
require("gitsigns-config")
require('oil-config')
require('cmake-config')
-- require('lua-dev-config')
require('null-ls-config')
require('trouble-config')
require('urlview-config')
require('mini-config')
require('nvim-lint-config')
require('devcontainer-config')
require('noice-config')
require('fasterbigfile-config')
require('aerial')
vim.cmd[[colorscheme tokyonight-night]]
end
require('dial-config')
require('leap-config')
require('surround-config')

