require('options')
require('keybindings')
require('plugins')
if not vim.g.vscode then
--require('avante-config')  -- Cargar avante temprano para que snacks esté disponible
require('blankline-config')
require('lsp')
require('lualine-config')
require('bufferline-config')
require('telescope-config')
require('octo-config')
require('dap-config')
require('live-preview-config')
require('terminal-config')
require('vscode-theme')
require("gitsigns-config")
require('oil-config')
require('cmake-config')
require('null-ls-config')
require('trouble-config')
require('urlview-config')
require('mini-config')
require('nvim-lint-config')
require('devcontainer-config')
--require('noice-config')
require('fasterbigfile-config')
require('render-markdown-config')
require('aerial')
require('mcphub-config')
require('orphans-config')
require('splitjoin-config')
require('copilot-config')
vim.cmd[[colorscheme tokyonight-night]]
end
require('dial-config')
require('leap-config')
require('surround-config')

